###
GET http://localhost:3000

###
GET http://localhost:3000/users

###
GET http://localhost:3000/api/users/68

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name":"Bekmambet",
    "age":24,
    "membershipstatus": "expired"
}

###
DELETE http://localhost:3000/api/users/78

###
PATCH  http://localhost:3000/api/users/77
Content-Type: application/json

{
    "name":"Scott",
    "age":44,
    "membershipstatus": "expired"
}